mpaas:
  scenarios:
    - name: FIRST_SCENARIO
      params:
        config: firstScenario.json
      tasks:
        - name: login
        - name: createConference
          params:
            config: createConf.json
        - name: timeWait
          params:
             time: 2000
        - name: createSession
          params:
            config: createSession.json
        - name: timeWait
          params:
            time: 1000
        - name: clientConnectSession


#    - name: SECOND_SCENARIO
#      params:
#        config: firstScenario.json
#      tasks:
#        - name: login
#        - name: createConference
#          params:
#            config: createConf.json
#        - name: createSession
#          params:
#            config: createSession.json
#        - name: discoverResources
#        - name: connectWebSocket
#        - name: subscribeToEvents
#        - name: activateCall
#          params:
#            config: activateCalls.json
#        - name: startAudioCall
#          params:
#            config: startAudioCall.json